Repository Xtao-Labs/PagerMaid_Plugins, pull requests merged in 2021-01, with the labels that each got.

#92 修复 pixiv 无法使用的问题。
  list.json
  xtao-some.py
Labels: bug

#93 关键词回复插件投稿
  keyword.py
  list.json
Labels: enhancement

#96 keyword 增加全局变量和正则捕获组
  keyword.py
  list.json
Labels: enhancement

#97 bug 修复
  keyword.py
  list.json
Labels: bug

#98 增加回复信息功能
  keyword.py
  list.json
Labels: enhancement

#102 调整：移除模板中的占位区域
  list.json
  throwit/1.png
  throwit/3.png
Labels: PR: awaiting review, bug
