Repository Xtao-Labs/PagerMaid_Plugins, pull requests merged in 2021-02, with the labels that each got.

#106 keyword 插件更新，允许对单个规则进行设置
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#107 keyword 更新，允许用规则序号删除规则
  keyword.py
  list.json
Labels: enhancement

#109 keyword 日常更新
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#110 keyword bug 修复
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review, bug

#111 keyword 更新，添加回复文件功能，添加频率限制
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#112 keyword 更新，允许群外回复
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#114 keyword 更新，添加函数功能
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#115 keyword 更新，函数改为异步
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#117 transfer 插件
  README.md
  list.json
  transfer.py
Labels: PR: author is committer, PR: awaiting review, enhancement

#118 keyword 更新，修复已知问题
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#119 添加未找到函数提示
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#120 keyword 插件的 newkeyword 函数
  keyword_func/list.json
  keyword_func/newkeyword.py
Labels: enhancement

#121 允许发送 TG 中包含的文件和图片
  keyword.py
  list.json
Labels: enhancement

#122 keyword 添加图片/文件缓存功能
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#123 更改函数存放目录
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review

#108 增加天气组件部分功能，更换ipping API
  list.json
  videodl.py
  weather.py
  xtao-some.py
Labels: PR: awaiting review, bug, enhancement

#113 修复 portball.py 远古 Bug
  portball.py
Labels: PR: author is committer, PR: awaiting review, bug

#124 keyword-beta
  avoid.py
  incoming.py
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review, enhancement

#125 添加删除回复信息的操作
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review, enhancement

#126 类似acg-multi等插件，内具一些美图，养眼
  list.json
  xjj.py
  zpr.py
Labels: PR: awaiting review, enhancement

#127 添加导入导出数据功能
  keyword.py
  list.json
Labels: PR: author is committer, PR: awaiting review, enhancement

#129 ✨ keyword maf 函数支持使用者触发关键词时回复其他用户
  keyword_func/maf.py
Labels: PR: author is committer, PR: awaiting review, enhancement
