Repository Xtao-Labs/PagerMaid_Plugins, pull requests merged in 2021-12, with the labels that each got.

#203 neteasedown 修复加载失败
  list.json
  neteasedown.py
Labels: bug, PR: awaiting review, PR: author is committer

#204 添加摸鱼插件
  list.json
  moyu.py
Labels: PR: awaiting review, PR: awaiting doc, PR: first-time contributor

#205 摸鱼插件添加更多图片
  list.json
  moyu.py
Labels: PR: awaiting review, PR: awaiting doc
