Repository Xtao-Labs/PagerMaid_Plugins, pull requests merged in 2022-01, with the labels that each got.

#209 ✨ `antichannelmsg` 支持按照以频道订阅人数进行删除并封禁
  antichannelmsg.py
  list.json
Labels: enhancement, pending

#210 ✨ Add silly_girl plugin
  list.json
  silly_girl.py
Labels: pending

#212 Update silly_girl.py
  list.json
  silly_girl.py
Labels: bug
